version: '3'

services:
        keycloak:
                container_name: keycloak_app
                image: jboss/keycloak
                restart: always
                ports:
                        - "8080:8080"
                        - "443:8443"
                volumes:
                        - "./certs/:/etc/x509/https"
                environment:
                        KEYCLOAK_USER: admin
                        KEYCLOAK_PASSWORD: <fill in>
                        KEYCLOAK_HTTP_PORT: 8080
                        KEYCLOAK_HTTPS_PORT: 443
                        KEYCLOAK_HOSTNAME: keycloak.example.com
